on: [push, pull_request]
name: ci
jobs:
  ut:
    name: unittest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_feature:
          - ""
          - "anyhow"
          - "backtrace"
          - "anyhow,backtrace"
        toolchain:
          - "stable"
          - "nightly"

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2

      - name: Setup | Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "${{ matrix.toolchain }}"
          override: true
          components: rustfmt, clippy

      - name: Unit Tests, with and without defensive store
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features "${{ matrix.test_feature }}"
        env:
          # To let stable rust use unstable features:
          # Thanks to @schreter
          # https://github.com/datafuselabs/openraft/issues/241#issuecomment-1060416327
          RUSTC_BOOTSTRAP: 1
          RUST_LOG: debug
          RUST_BACKTRACE: full

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          path: |
            _log/

  checks:
    name: other checks
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2


      - name: Setup | Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "nightly"
          override: true
          components: rustfmt, clippy


      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features


      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check


      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets -- -D warnings -A clippy::bool-assert-comparison